#!/usr/bin/env python3

import time
import cmd
import argparse
from pyvicp import Client


def request_response(scope, request):
    if isinstance(request, str):
        request = request.encode()
    scope.send(request)
    return scope.receive()


class LecroyShell(cmd.Cmd):
    def __init__(self, scope):
        cmd.Cmd.__init__(self)
        self.scope = scope

    def do_exit(self, _):
        exit(0)

    def do_quit(self, _):
        exit(0)

    def do_q(self, _):
        exit(0)

    def default(self, command):
        operation, *_ = command.split(" ")
        command = command.encode()

        if operation.endswith("?"):
            try:
                start = time.time()
                result = request_response(self.scope, command)
                stop = time.time()
            except TimeoutError:
                print("Timeout")
                return
            delta = stop - start

            if len(result) > 200:
                result = result[:100] + b" ... " + result[-100:]

            if result.isascii():
                result = result.decode().strip()

            print(f"[{delta:.1f} s] {result}")
        else:
            self.scope.send(command)


def main():
    parser = argparse.ArgumentParser(
        description="Provides a console to send SCPI commands "
                    "to Lecroy scopes using VICP")
    parser.add_argument("ip", help="IP address of scope")
    args = parser.parse_args()

    # for some reason, the constructor does not initialize the timeout properly
    timeout = 5.0
    scope = Client(args.ip, timeout=timeout)
    scope.timeout = timeout
    LecroyShell(scope).cmdloop()


if __name__ == "__main__":
    main()
